---
 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-deployment
  labels:
    app: health-care
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
        - name: health-care-container
          image: pj013525/health-care:v1
          ports:
            - containerPort: 8082     # ← FIXED
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: health-care-service
spec:
  selector:
    app: health-care
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082              # ← FIXED
  type: NodePort

     
     
